nation3/citizen-app

- ui/lib/liquidity-rewards.js
- Compute APY based on the value of the LP tokens deposited on the contract instead of the total pool value
- Sort operations to increase precision
> Fix rewards APY calculation

- ui/components/Layout.tsx
> fix(ui): Fixes #52

- ui/components/Layout.tsx
- ui/components/PassportCheck.tsx
- Adds PassportCheck component
- Conditionally wraps Layout in a passport check
Since the `useContractRead` was throwing an error rather than returning one in its response data, the only solution was to conditionally render a component to call the hook only when satisfactory conditions are met i.e. a user address exists.
Fixes #54
> fix(Layout): Fixes error when no address available

- ui/lib/passport-nft.ts
- ui/pages/citizen.tsx
I was puzzled why the Citizen page still looked the same after the PR being merged, and it was because of a faulty merge previously. This PR adds the new layout for the Citizen page.
> fix(ui): Fix merge issue resulting in old citizen layout being displayed

- ui/.eslintrc
- ui/components/ActionButton.tsx
- ui/components/ActionNeedsTokenApproval.tsx
- ui/components/PassportCheck.tsx
- ui/lib/static-call.ts
- ui/lib/use-handle-error.ts
- ui/lib/use-preferred-network.ts
- ui/lib/ve-token.ts
- ui/pages/lock.tsx
Task details: https://app.dework.xyz/nation3/citizen-app-p?taskId=169960b2-e749-44fc-8553-c1f409b84a32
> Fix yarn lint warnings

- .github/workflows/ui_goerli.yml
- .github/workflows/ui_mainnet.yml
- ui/cypress.config.ts
- ui/package.json
- ui/yarn.lock
https://app.dework.xyz/nation3/develop-1?taskId=6e23da02-1be9-49db-976b-e74c72846324
close #87 
```
yarn e2e:headless
```
```
====================================================================================================
(Run Finished)
Spec                                              Tests  Passing  Failing  Pending  Skipped  
┌────────────────────────────────────────────────────────────────────────────────────────────────┐
│ ✔  app.cy.ts                                00:53        5        5        -        -        - │
└────────────────────────────────────────────────────────────────────────────────────────────────┘
✔  All specs passed!                        00:53        5        5        -        -        -  
✨  Done in 101.38s.
```
> test(cypress): start server on localhost (#87)

- ui/components/EthersInput.tsx
- ui/cypress/e2e/lock.cy.ts
- ui/lib/numbers.test.ts
- ui/lib/numbers.ts
- ui/package.json
- ui/pages/liquidity.tsx
- ui/pages/lock.tsx
- ui/yarn.lock
https://app.dework.xyz/nation3/app-2?taskId=a30b52d5-e12b-4ebe-8f3f-664aa84a158a
Issue #94 
Try to use inputs on `liquidity` or `lock` page, entering numbers with more than 18 decimals. The value should stop changing after 18 decimals
> NUMERIC_FAULT error

- ui/components/Layout.tsx
https://github.com/github/renaming
> refactor: rename from master to main

- ui/pages/lock.tsx
https://app.dework.xyz/nation3/citizen-app-p?taskId=f614e270-4baf-4e1a-80d7-a6a9f3ad1234
#71
> ![IMG_0105](https://user-images.githubusercontent.com/95955389/191215233-e4c34c12-00ea-4682-8fa1-92513b36ab00.jpeg)
> Correct info text on /lock page

- ui/pages/lock.tsx
https://app.dework.xyz/nation3/app-2?taskId=c76a4e30-ca38-4c25-bce1-fc21fb172254
Fixes #114
> Fix lock page calculation

- ui/pages/lock.tsx
https://app.dework.xyz/nation3/app-2?taskId=d0898a65-ad04-4d76-917d-a2db61d10efb
Fixes https://github.com/nation3/app/issues/124
> Fix lock page type errors

- ui/components/Layout.tsx
- ui/lib/config.ts
Fixes https://github.com/nation3/app/issues/123
> Add etherscan domain to config

- ui/components/ActionNeedsTokenApproval.tsx
- ui/components/Layout.tsx
- ui/components/PassportExpiration.tsx
- ui/components/SwitchNetworkBanner.tsx
- ui/package.json
- ui/pages/index.tsx
- ui/pages/join.tsx
- ui/pages/liquidity.tsx
- ui/pages/lock.tsx
- ui/yarn.lock
[](https://app.dework.xyz/nation3/develop-1?taskId=0d4cc230-f502-4744-859f-b21c010921c1)
[](https://github.com/nation3/app/issues/134)
Ran application to ensure no breaking changes
> Tonyalpha/dw 799/upgrade heroiconsreact

- ui/components/ActionButton.tsx
- ui/components/ActionNeedsTokenApproval.tsx
- ui/components/AllowanceWarning.tsx
- ui/pages/lock.tsx
This is not related to any task in specific.
If anyone want more context feel free to DM.
Running UI on local with goerli tesnet.
> feat(lock): Limit the allowance for veNATION transfers

- ui/pages/citizen.tsx
- chore: prettier citizen page codebase
- fix(citizen): Fix layout for actions in small devices
Before:
After:
> fix passport actions sm layout

- ui/lib/approve.ts
Fix unhandled runtime error introduced in #147
https://app.dework.xyz/nation3/citizen-app-p?taskId=f39147d2-96d7-4423-8473-8f0a9db82628
closes #148
Before:
After:
```
yarn cypress
```
```
yarn cypress:headless
```
```
javascript
====================================================================================================
(Run Finished)
Spec                                              Tests  Passing  Failing  Pending  Skipped  
┌────────────────────────────────────────────────────────────────────────────────────────────────┐
│ ✔  app.cy.ts                                00:25        4        4        -        -        - │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  lock.cy.ts                               00:07        1 …
```
> fix(wagmi): handle uncaught error (#147)

- ui/.prettierrc.json
- ui/components/ErrorProvider.tsx
- ui/components/EthersInput.tsx
- ui/components/Layout.tsx
- ui/components/MainCard.tsx
- ui/components/PassportExpiration.tsx
- ui/pages/citizen.tsx
- ui/pages/index.tsx
- ui/pages/join.tsx
- ui/pages/liquidity.tsx
Simply apply prettier formatter.
> style: Prettify code at once to avoid formatter introducing noise in PRs

- ui/lib/config.ts
- ui/pages/index.tsx
- ui/pages/lock.tsx
Remove code related to the `$veNATION` rewards multiplier
https://app.dework.xyz/nation3/develop-1?taskId=6e7e7e5c-7aee-4934-af85-6867f87fc2de
#158, #160
> <img width="835" alt="Screenshot 2022-12-15 at 1 44 51 PM" src="https://user-images.githubusercontent.com/95955389/207785195-59b3a020-0ec3-4e83-9b4f-ca80351d8388.png">
> <img width="831" alt="Screenshot 2022-12-15 at 1 45 15 PM" src="https://user-images.githubusercontent.com/95955389/207785203-1bcd7586-02ed-4cfc-b544-f3df33814a81.png">
---
> <img width="611" alt="Screenshot 2022-12-15 at 1 47 27 PM" src="https://user-images.githubusercontent.com/95955389/207785207-3329a05e-4163-4eae-a6a8-6e6b00f20ceb.png">
> <img width="616" alt="Screenshot 2022-12-15 at 1 47 48 PM" src="https://user-images.githubusercontent.com/95955389/207785208-7477f …
> Remove code related to the $veNATION rewards multiplier

- ui/lib/connectors.ts
Fix typo introduced in https://github.com/nation3/app/commit/e01da4aab773c58797488068fe496515bf0fca33
> Fix wagmi provider typo

- ui/components/Layout.tsx
https://app.dework.xyz/bounties?taskId=b0e07f30-c664-46c4-b6e2-0b9fb9422ce5
https://github.com/nation3/app/issues/185
reversed the process of integration https://splitbee.io/docs/embed-the-script
> Remove Splitbee script

- contracts/deployments/goerli.json
- contracts/deployments/mainnet.json
- ui/lib/config.ts
- ui/lib/passport-expiration-hook.ts
- ui/lib/passport-nft.ts
[](https://app.dework.xyz/nation3/open-bounties-95838?taskId=07770dc2-1903-4b46-8a94-70d408845e86)
https://app.dework.xyz/nation3/open-bounties-95838?taskId=07770dc2-1903-4b46-8a94-70d408845e86
[GitHub issue:](https://github.com/nation3/app/issues/226) #226 
I have run the code and it compiles successfully. I also checked the citizen route. It has been thoroughly tested through a combination of unit tests, integration tests, manual testing, and peer reviews. The testing process ensures the stability and reliability of the changes.
> Remove nationPassportRevokeUnderBalance from config, fetch smart contract data

- .github/workflows/ui_sepolia.yml
https://app.dework.xyz/nation3/development-guild-43499?taskId=28308d89-f718-467d-9306-3efc01daf7ed
> test: goerli --> sepolia

- .github/workflows/ui_mainnet.yml
- .github/workflows/ui_sepolia.yml
> test: add node v20

- ui/components/Layout.tsx
> chore: link to wiki

- ui/components/Layout.tsx
> ![image](https://github.com/nation3/citizen-app/assets/95955389/d5c59cf4-d3cc-4e71-ae20-ab992b7546b2)
> Link to citizen directory

- ui/components/Layout.tsx
> Add link to income.nation3.org

- contracts/deployments/sepolia.json
> chore: update liquidity rewards

- contracts/deployments/sepolia.json
> sepolia: lp rewards

- ui/pages/lock.tsx
> "at least" --> "more than"

- ui/pages/index.tsx
- ui/pages/join.tsx
> fix: balancer url

- ui/components/SwitchNetworkBanner.tsx
> ⚠️ improve network message

- ui/package.json
Tests running ok with cypress 11, no changes are required.
https://github.com/nation3/citizen-app/issues/287
> upgrade cypress to 11
